name: Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Create API documentation
        run: pnpm run build:typedoc

      - name: Build with Qgoda
        uses: gflohr/qgoda-action@v1
        with:
          qgoda-version: latest-node
          qgoda-srcdir: packages/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/_site/e-invoice-eu
